/*

~ Facebook Home Page 100% on Javascript
~ This project is made for measure my skills in Javascript
~ I will not use mediaqueries (The optime resolution is 1280x800)
~ Edgar de Jesús Luna Chima Web Developer Junior 2021
~ I hope you like it <3

*/

// Tag creation

console.log("Creating Elements")
const metaUTF8 = document.createElement("meta")
const linkShortcutImage = document.createElement("link")
const title = document.createElement("title")
const logoContainer = document.createElement("div")
const facebookLogo = document.createElement("img")
const h2 = document.createElement("h2")
const formRegister = document.createElement("form")
const inputEmail = document.createElement("input")
const inputPassword = document.createElement("input")
const inputSubmit = document.createElement("input")
const divSeparator = document.createElement("div")
const lostPassword = document.createElement("a")
const createNewAccount = document.createElement("a")
const pageRegister = document.createElement("a")
const footer = document.createElement("footer")
const languageList = document.createElement("ul")
const languageSpanish = document.createElement("li")
const languageEnglish = document.createElement("li")
const languageFrench = document.createElement("li")
const languagePortuguese = document.createElement("li")
const languageItalian = document.createElement("li")
const languageGerman = document.createElement("li")
const languageArab = document.createElement("li")
const languageHindu = document.createElement("li")
const languageSimplifiedChinese = document.createElement("li")
const languageJapanese = document.createElement("li")
const moreLanguages = document.createElement("a")
const tagIgnore = document.createElement("ul")
const tagRegister = document.createElement("li")
const tagLogIn = document.createElement("li")
const tagMessenger = document.createElement("li")
const tagFacebookLite = document.createElement("li")
const tagWatch = document.createElement("li")
const tagPeople = document.createElement("li")
const tagPages = document.createElement("li")
const tagPagesCategories = document.createElement("li")
const tagPlaces = document.createElement("li")
const tagGames = document.createElement("li")
const tagLocations = document.createElement("li")
const tagMarketplace = document.createElement("li")
const tagPay = document.createElement("li")
const tagGroups = document.createElement("li")
const tagJobs = document.createElement("li")
const tagOculus = document.createElement("li")
const tagPortal = document.createElement("li")
const tagInstagram = document.createElement("li")
const tagLocal = document.createElement("li")
const tagFundraisers = document.createElement("li")
const tagServices = document.createElement("li")
const tagVotingInfoCenter = document.createElement("li")
const tagAbout = document.createElement("li")
const tagCreateAd = document.createElement("li")
const tagCreatePage = document.createElement("li")
const tagDevelopers = document.createElement("li")
const tagCarrers = document.createElement("li")
const tagPrivacy = document.createElement("li")
const tagCookies = document.createElement("li")
const tagAdChoice = document.createElement("li")
const adChoiceImg = document.createElement("img")
const tagTerms = document.createElement("li")
const tagHelp = document.createElement("li")
const anchorLanguageSpanish = document.createElement("a")
const anchorLanguageEnglish = document.createElement("a")
const anchorLanguageFrench = document.createElement("a")
const anchorLanguagePortuguese = document.createElement("a")
const anchorLanguageItalian = document.createElement("a")
const anchorLanguageGerman = document.createElement("a")
const anchorLanguageArab = document.createElement("a")
const anchorLanguageHindu = document.createElement("a")
const anchorLanguageSimplifiedChinese = document.createElement("a")
const anchorLanguageJapanese = document.createElement("a")
const anchorTagRegister = document.createElement("a")
const anchorTagLogIn = document.createElement("a")
const anchorTagMessenger = document.createElement("a")
const anchorTagFacebookLite = document.createElement("a")
const anchorTagWatch = document.createElement("a")
const anchorTagPeople = document.createElement("a")
const anchorTagPages = document.createElement("a")
const anchorTagPagesCategories = document.createElement("a")
const anchorTagPlaces = document.createElement("a")
const anchorTagGames = document.createElement("a")
const anchorTagLocations = document.createElement("a")
const anchorTagMarketplace = document.createElement("a")
const anchorTagPay = document.createElement("a")
const anchorTagGroups = document.createElement("a")
const anchorTagJobs = document.createElement("a")
const anchorTagOculus = document.createElement("a")
const anchorTagPortal = document.createElement("a")
const anchorTagInstagram = document.createElement("a")
const anchorTagLocal = document.createElement("a")
const anchorTagFundraisers = document.createElement("a")
const anchorTagServices = document.createElement("a")
const anchorTagVotingInfoCenter = document.createElement("a")
const anchorTagAbout = document.createElement("a")
const anchorTagCreateAd = document.createElement("a")
const anchorTagCreatePage = document.createElement("a")
const anchorTagDevelopers = document.createElement("a")
const anchorTagCarrers = document.createElement("a")
const anchorTagPrivacy = document.createElement("a")
const anchorTagCookies = document.createElement("a")
const anchorTagAdChoice = document.createElement("a")
const anchorTagTerms = document.createElement("a")
const anchorTagHelp = document.createElement("a")
console.log("Elements Created Sucefully")

// Text Node Creation

console.log("Creating Text")
const textTitle = document.createTextNode("Facebook - Inicia sesión o Regístrate.")
const textH2 = document.createTextNode("Connect with friends and the world around you on Facebook.")
const textInputSubmit = document.createTextNode("Log In")
const textLostPassword = document.createTextNode("Forgot Password?")
const textCreateNewAccount = document.createTextNode("Create New Account")
const textPageRegister = document.createTextNode("Create a Page")
const textLanguageSpanish = document.createTextNode("Español")
const textLanguageEnglish = document.createTextNode("English (US)")
const textLanguageFrench = document.createTextNode("Français (France)")
const textLanguagePortuguese = document.createTextNode("Português (Brasil)")
const textLanguageItalian = document.createTextNode("Italiano")
const textLanguageGerman = document.createTextNode("Deutsch")
const textLanguageArab = document.createTextNode("لعربية")
const textLanguageHindu = document.createTextNode("हिन")
const textLanguageSimplifiedChinese = document.createTextNode("中文(简体)")
const textLanguageJapanese = document.createTextNode("日本語")
const textTagRegister = document.createTextNode("Sign Up")
const textTagLogIn = document.createTextNode("Log In")
const textTagMessenger = document.createTextNode("Messenger")
const textTagFacebookLite = document.createTextNode("Facebook Lite")
const textTagWatch = document.createTextNode("Watch")
const textTagPeople = document.createTextNode("People")
const textTagPages = document.createTextNode("Pages")
const textTagPagesCategories = document.createTextNode("Page Categories")
const textTagPlaces = document.createTextNode("Places")
const textTagGames = document.createTextNode("Games")
const textTagLocations = document.createTextNode("Locations")
const textTagMarketplace = document.createTextNode("Marketplace")
const textTagPay = document.createTextNode("Facebook Pay")
const textTagGroups = document.createTextNode("Groups")
const textTagJobs = document.createTextNode("Jobs")
const textTagOculus = document.createTextNode("Oculus")
const textTagPortal = document.createTextNode("Portal")
const textTagInstagram = document.createTextNode("Instagram")
const textTagLocal = document.createTextNode("Local")
const textTagFundraisers = document.createTextNode("Fundraisers")
const textTagServices = document.createTextNode("Services")
const textTagVotingInfoCenter = document.createTextNode("Voting Information Center")
const textTagAbout = document.createTextNode("About")
const textTagCreateAd = document.createTextNode("Create Ad")
const textTagCreatePage = document.createTextNode("Create Page")
const textTagDevelopers = document.createTextNode("Developers")
const textTagCarrers = document.createTextNode("Carrers")
const textTagPrivacy = document.createTextNode("Privacy")
const textTagCookies = document.createTextNode("Cookies")
const textTagAdChoice = document.createTextNode("Ad Choices")
const textTagTerms = document.createTextNode("Terms")
const textTagHelp = document.createTextNode("Help")
console.log("Texts Created Sucefully")

// Append text to nodes

console.log("Appending Text")
const titleFinal = title.appendChild(textTitle).textContent
const h2Final = h2.appendChild(textH2)
const inputSubmitFinal = inputSubmit.appendChild(textInputSubmit)
const lostPasswordFinal = lostPassword.appendChild(textLostPassword)
const createNewAccountFinal = createNewAccount.appendChild(textCreateNewAccount)
const pageRegisterFinal = pageRegister.appendChild(textPageRegister)
// const languageSpanishFinal = languageSpanish.appendChild(textLanguageSpanish)
a= anchorLanguageSpanish.appendChild(textLanguageSpanish)
const languageSpanishFinal = languageSpanish.appendChild(a)
const languageEnglishFinal = languageEnglish.appendChild(textLanguageEnglish)
const languageFrenchFinal = languageFrench.appendChild(textLanguageFrench)
const languagePortugueseFinal = languagePortuguese.appendChild(textLanguagePortuguese)
const languageItalianFinal = languageItalian.appendChild(textLanguageItalian)
const languageGermanFinal = languageGerman.appendChild(textLanguageGerman)
const languageArabFinal = languageArab.appendChild(textLanguageArab)
const languageHinduFinal = languageHindu.appendChild(textLanguageHindu)
const languageSimplifiedChineseFinal = languageSimplifiedChinese.appendChild(textLanguageSimplifiedChinese)
const languageJapaneseFinal = languageJapanese.appendChild(textLanguageJapanese)
const tagRegisterFinal = tagRegister.appendChild(textTagRegister)
const tagLogInFinal = tagLogIn.appendChild(textTagLogIn)
const tagMessengerFinal = tagMessenger.appendChild(textTagMessenger)
const tagFacebookLiteFinal = tagFacebookLite.appendChild(textTagFacebookLite)
const tagWatchFinal = tagWatch.appendChild(textTagWatch)
const tagPeopleFinal = tagPeople.appendChild(textTagPeople)
const tagPagesFinal = tagPages.appendChild(textTagPages)
const tagPagesCategoriesFinal = tagPagesCategories.appendChild(textTagPagesCategories)
const tagPlacesFinal = tagPlaces.appendChild(textTagPlaces)
const tagGamesFinal = tagGames.appendChild(textTagGames)
const tagLocationsFinal = tagLocations.appendChild(textTagLocations)
const tagMarketplaceFinal = tagMarketplace.appendChild(textTagMarketplace)
const tagPayFinal = tagPay.appendChild(textTagPay)
const tagGroupsFinal = tagGroups.appendChild(textTagGroups)
const tagJobsFinal = tagJobs.appendChild(textTagJobs)
const tagOculusFinal = tagOculus.appendChild(textTagOculus)
const tagPortalFinal = tagPortal.appendChild(textTagPortal)
const tagInstagramFinal = tagInstagram.appendChild(textTagInstagram)
const tagLocalFinal = tagLocal.appendChild(textTagLocal)
const tagFundraisersFinal = tagFundraisers.appendChild(textTagFundraisers)
const tagServicesFinal = tagServices.appendChild(textTagServices)
const tagVotingInfoCenterFinal = tagVotingInfoCenter.appendChild(textTagVotingInfoCenter)
const tagAboutFinal = tagAbout.appendChild(textTagAbout)
const tagCreateAdFinal = tagCreateAd.appendChild(textTagCreateAd)
const tagCreatePageFinal = tagCreatePage.appendChild(textTagCreatePage)
const tagDevelopersFinal = tagDevelopers.appendChild(textTagDevelopers)
const tagCarrersFinal = tagCarrers.appendChild(textTagCarrers)
const tagPrivacyFinal = tagPrivacy.appendChild(textTagPrivacy)
const tagCookiesFinal = tagCookies.appendChild(textTagCookies)
const tagAdChoiceFinal = tagAdChoice.appendChild(textTagAdChoice)
const tagTermsFinal = tagTerms.appendChild(textTagTerms)
const tagHelpFinal = tagHelp.appendChild(textTagHelp)


console.log("Text Appended Sucefully")

// Append to the parents nodes

console.log("Appending Elements")
document.title = titleFinal
document.head.appendChild(metaUTF8)
document.head.appendChild(linkShortcutImage)
document.body.appendChild(facebookLogo)
document.body.appendChild(h2)
document.body.appendChild(formRegister)
formRegister.appendChild(inputEmail)
formRegister.appendChild(inputPassword)
formRegister.appendChild(inputSubmit)
formRegister.appendChild(divSeparator)
formRegister.appendChild(lostPassword)
formRegister.appendChild(createNewAccount)
document.body.appendChild(pageRegister)
document.write(" for a celebrity, band or business.")
document.body.appendChild(languageList)
languageList.appendChild(languageSpanishFinal)
languageList.appendChild(languageEnglish)
languageList.appendChild(languageFrench)
languageList.appendChild(languagePortuguese)
languageList.appendChild(languageItalian)
languageList.appendChild(languageGerman)
languageList.appendChild(languageArab)
languageList.appendChild(languageHindu)
languageList.appendChild(languageSimplifiedChinese)
languageList.appendChild(languageJapanese)
document.body.appendChild(moreLanguages)
document.body.appendChild(divSeparator)
document.body.appendChild(tagIgnore)
tagIgnore.appendChild(tagRegister)
tagIgnore.appendChild(tagLogIn)
tagIgnore.appendChild(tagMessenger)
tagIgnore.appendChild(tagFacebookLite)
tagIgnore.appendChild(tagWatch)
tagIgnore.appendChild(tagPeople)
tagIgnore.appendChild(tagPages)
tagIgnore.appendChild(tagPagesCategories)
tagIgnore.appendChild(tagPlaces)
tagIgnore.appendChild(tagGames)
tagIgnore.appendChild(tagLocations)
tagIgnore.appendChild(tagMarketplace)
tagIgnore.appendChild(tagPay)
tagIgnore.appendChild(tagGroups)
tagIgnore.appendChild(tagJobs)
tagIgnore.appendChild(tagOculus)
tagIgnore.appendChild(tagPortal)
tagIgnore.appendChild(tagInstagram)
tagIgnore.appendChild(tagLocal)
tagIgnore.appendChild(tagFundraisers)
tagIgnore.appendChild(tagServices)
tagIgnore.appendChild(tagVotingInfoCenter)
tagIgnore.appendChild(tagAbout)
tagIgnore.appendChild(tagCreateAd)
tagIgnore.appendChild(tagCreatePage)
tagIgnore.appendChild(tagDevelopers)
tagIgnore.appendChild(tagCarrers)
tagIgnore.appendChild(tagPrivacy)
tagIgnore.appendChild(tagCookies)
tagIgnore.appendChild(tagAdChoice)
tagIgnore.appendChild(tagTerms)
tagIgnore.appendChild(tagHelp)
console.log("Elements Appended Sucefully")

// Set attributes

console.log("Setting Attributes")
metaUTF8.setAttribute("charset","UTF-8")
linkShortcutImage.setAttribute("rel","shortcut icon")
linkShortcutImage.setAttribute("href","img/logo.png")
facebookLogo.setAttribute("src","img/FacebookLogo.svg")


console.log("Attributes Setted Sucefully")